<a href="https://colab.research.google.com/github/Stepeech/DataMining/blob/main/1_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,102,2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
a = np.random.random(5)
print(a)
a = a[::-1]
print(a)

[0.83846092 0.87014244 0.63276202 0.51798071 0.42448207]
[0.42448207 0.51798071 0.63276202 0.87014244 0.83846092]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
a = np.zeros(16).reshape(4,4)
a = np.diag(np.ones(3), k = 1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
a = np.diag(np.arange(1,5))
a[a==0] = 7
print(a)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
a = np.zeros((5,5))
b = np.arange(5)
print(a+b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
a = np.random.random((10,10))
b = a - a.mean(axis=1)
print(b)

[[-0.22449015 -0.49878648 -0.06767343  0.23331601 -0.2704804  -0.01595814
   0.27556558 -0.22660623 -0.43696051  0.03879109]
 [ 0.12895942  0.32951616 -0.25382919  0.40441465  0.05855661 -0.12512646
   0.44106824 -0.02340933  0.44177159 -0.54818221]
 [ 0.13489562 -0.35533838  0.47629471 -0.25514008 -0.45101892 -0.38526184
   0.30650672  0.12539782 -0.43416933  0.04928944]
 [ 0.10419797 -0.52450855  0.38283684  0.41403874 -0.22906998  0.03918872
   0.16362087  0.17062428 -0.13201242  0.16188139]
 [ 0.34144569 -0.0108149   0.02127695 -0.14356971 -0.32021126 -0.4417866
   0.32804929 -0.06510851 -0.3326774   0.12029114]
 [-0.22903497  0.10815763 -0.27360491 -0.1927801   0.48394128 -0.20034859
   0.40996423  0.34128555  0.36236968  0.0210072 ]
 [ 0.13596791  0.06999072  0.06681818 -0.21324988 -0.32885414  0.37271778
  -0.06606946 -0.3005411   0.346684    0.03300321]
 [ 0.08143836 -0.32488812 -0.30126826 -0.5307987  -0.16975082  0.01773126
   0.38100129  0.46346876  0.31434569 -0.0864776 ]
 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
a = np.random.random((10,10))
b = a - np.median(a, axis=0)

print(b)

[[-0.25105993  0.0559487   0.19743995  0.26195982 -0.07786137  0.37681694
  -0.02608833  0.00219243  0.40812657  0.26696631]
 [-0.26531232 -0.32599088 -0.33381593  0.08994384  0.03614862 -0.07134678
  -0.21034966 -0.00219243  0.49598175 -0.09780308]
 [ 0.18373444 -0.0559487   0.22893968 -0.56281348 -0.35845935  0.38185403
  -0.28289727 -0.27219084  0.22994959  0.0936396 ]
 [ 0.41155161 -0.53017141  0.24027619 -0.56420422  0.36461303 -0.2664263
   0.26127714  0.44474392 -0.26414073 -0.37207466]
 [-0.01583398  0.2151267   0.29643089  0.30594033 -0.30221823 -0.13156203
   0.41033971 -0.25030911 -0.08653211  0.3092848 ]
 [-0.2330297  -0.51642337 -0.37449757 -0.03295666  0.5760828   0.1112751
   0.01753204  0.2677871   0.08653211 -0.16705137]
 [-0.38237555  0.08337154  0.08899682 -0.30715333 -0.3940518   0.23900795
  -0.23588818 -0.02636053 -0.12402216 -0.0936396 ]
 [ 0.39058186 -0.54725305 -0.08899682  0.39506687 -0.03614862  0.00373417
   0.12513454  0.30494038 -0.0870733   0.26969665]
 [

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
a = np.random.random((5,5))
max = np.array([np.max(a, axis=1)])
min = np.array([np.min(a, axis=1)])

a = np.hstack((a, max.T, min.T))
print(a)

[[0.97097572 0.73707742 0.78451592 0.87338573 0.71432644 0.97097572
  0.71432644]
 [0.30701793 0.21702527 0.45417157 0.61354188 0.64912449 0.64912449
  0.21702527]
 [0.46052631 0.79774614 0.40022333 0.59170534 0.75139491 0.79774614
  0.40022333]
 [0.92387888 0.79585045 0.53621562 0.69615014 0.56784787 0.92387888
  0.53621562]
 [0.1431674  0.124189   0.09009995 0.85020971 0.0310134  0.85020971
  0.0310134 ]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
a = np.arange(1,51)

b = np.array([[x for x in a if x%2]])
c = np.array([[x for x in a if not x%2]])

b = b.reshape((5,5))
c = c.reshape((5,5))

bc = b*c
print(bc)

print(np.linalg.det(bc)) #определитель равен нулю, поэтому матрица не может быть инвентирована

#print(np.linalg.inv(bc))

[[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]
0.0


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
a = np.zeros((8,8))
a[0::2, 0::2] = 1
a[1::2, 1::2] = 1

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
